version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Dina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
